name: kotodama-lab
favicon: null
layout_spectrum: 0.94004
typography_spectrum: 0.63256
title: Kotodama Lab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2663911380805075
  lightness: 0.20030426373705268
  saturation: 0.5205874210223556
  rhythmicContrast: 0.1865484258159995
purpose: []
