name: kotodama-lab
favicon: null
layout_spectrum: 0.00232
typography_spectrum: 0.63256
title: Kotodama Lab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#160a14'
    - '#ac999d'
    - '#6b5c5f'
    - '#fafbfd'
    - '#c34551'
  brandStrength: 0.25
  lightness: 0.9375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
